baseURL = "https://vibrant-williams-d83705.netlify.app/"
languageCode = "en-us"
title = "Group 2 Site"
theme = "ananke"

[menu]
[[main.menu]]
identifier = 'coffee shop'
name = 'Wildcat Cafe'
title = 'coffee section'
url = '/"https://vibrant-williams-d83705.netlify.app/'
weight = -110



[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.74.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.74.3"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.74.3"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.74.3"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

